name: Testing
on: push

jobs:
    testing_project:
        runs-on: windows
        steps:
        - uses: actions/checkout
        - name: Run Django unit tests
          run: |
            pip3 install --user django
            python3 manage.py test