name: Testing
on: push

jobs:
    test_project:
        runs-on: windows 10-latest
        steps:
        - uses: actions/checkout
        - name: Run Django unit tests
          run: |
            pip3 install --user django
            python3 manage.py test
                
                